"""
Django settings for Edventure project.
Generated by 'django-admin startproject' using Django 5.2.5.
"""
import os
from pathlib import Path

# -----------------------
# BASE DIRECTORY
# -----------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------
# SECURITY SETTINGS
# -----------------------
SECRET_KEY = 'django-insecure-e#t(_7l14_o=)j#1v=!!_=!tp_#ml+p(^el6jjvztp62r+k_!+'
DEBUG = True
ALLOWED_HOSTS = []

# -----------------------
# INSTALLED APPS
# -----------------------
INSTALLED_APPS = [
    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Your apps
    'accounts',
    'api',
    'ml',

    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# -----------------------
# MIDDLEWARE
# -----------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------
# URL & WSGI
# -----------------------
ROOT_URLCONF = 'Edventure.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [BASE_DIR / "templates"],  # You can put template folders here later
        # 'DIRS': [os.path.join(BASE_DIR, "react-frontend/dist")],
        'DIRS': [BASE_DIR / "react-frontend" / "dist"],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Edventure.wsgi.application'

# -----------------------
# DATABASE
# -----------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Use SQLite for now
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -----------------------
# PASSWORD VALIDATION
# -----------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -----------------------
# INTERNATIONALIZATION
# -----------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------
# STATIC FILES
# -----------------------

# -----------------------
# STATIC FILES
# -----------------------
STATIC_URL = '/assets/'  # Changed from 'static/' to match Vite's output
STATICFILES_DIRS = [
    BASE_DIR / "react-frontend" / "dist",  # Remove "assets" from path
]

# STATIC_URL = 'static/'
# STATICFILES_DIRS = [
#     BASE_DIR / "react-frontend" / "dist" / "assets",
# #    os.path.join(BASE_DIR, "react-frontend/dist/assets")
#     # BASE_DIR / "static",  # For static assets like CSS, JS, images
# ]

# -----------------------
# DEFAULT PRIMARY KEY
# -----------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------
# CORS HEADERS SETTINGS
# -----------------------
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins during development


# -----------------------
# APP BRANDING
# -----------------------
APP_NAME = "Edventure"  # or whatever your store name is
import os
from dotenv import load_dotenv

load_dotenv()  # load .env

# GOOGLE_API_KEY = os.getenv("AIzaSyBcnj3kWdzJVeDyH2WTpNx3u95Yc17YFdI")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

CORS_ALLOW_ALL_ORIGINS = True
if not GOOGLE_API_KEY:
    print("⚠️ WARNING: GOOGLE_API_KEY is not set. Add it to your .env file!")

